function createhggroup(XData1, YData1, XData2, YData2, XData3, YData3, XData4, YData4, XData5, YData5, XData6, YData6, XData7, YData7, XData8, YData8, XData9, YData9, YData10, YData11, YData12, YData13, YData14, YData15, YData16, YData17, YData18, XData10, YData19, XData11, YData20, XData12, YData21, XData13, YData22, XData14, YData23, XData15, YData24, XData16, YData25, XData17, YData26, XData18, YData27, YData28, YData29, YData30, YData31, YData32, YData33, YData34, YData35, XData19, YData36, XData20, YData37, XData21, YData38, XData22, YData39, XData23, YData40, XData24, YData41, XData25, YData42, XData26, YData43, XData27, YData44, XData28, YData45, XData29, YData46, XData30, YData47, XData31, YData48, XData32, YData49, XData33, YData50, XData34, YData51, XData35, YData52, XData36, YData53, YData54, XData37, YData55, XData38, YData56, XData39, YData57, XData40, YData58, XData41, YData59, XData42, YData60, XData43, YData61, XData44, YData62)
%CREATEHGGROUP(XData1, YData1, XData2, YData2, XData3, YData3, XData4, YData4, XData5, YData5, XData6, YData6, XData7, YData7, XData8, YData8, XData9, YData9, YData10, YData11, YData12, YData13, YData14, YData15, YData16, YData17, YData18, XData10, YData19, XData11, YData20, XData12, YData21, XData13, YData22, XData14, YData23, XData15, YData24, XData16, YData25, XData17, YData26, XData18, YData27, YData28, YData29, YData30, YData31, YData32, YData33, YData34, YData35, XData19, YData36, XData20, YData37, XData21, YData38, XData22, YData39, XData23, YData40, XData24, YData41, XData25, YData42, XData26, YData43, XData27, YData44, XData28, YData45, XData29, YData46, XData30, YData47, XData31, YData48, XData32, YData49, XData33, YData50, XData34, YData51, XData35, YData52, XData36, YData53, YData54, XData37, YData55, XData38, YData56, XData39, YData57, XData40, YData58, XData41, YData59, XData42, YData60, XData43, YData61, XData44, YData62)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  XDATA3:  line xdata
%  YDATA3:  line ydata
%  XDATA4:  line xdata
%  YDATA4:  line ydata
%  XDATA5:  line xdata
%  YDATA5:  line ydata
%  XDATA6:  line xdata
%  YDATA6:  line ydata
%  XDATA7:  line xdata
%  YDATA7:  line ydata
%  XDATA8:  line xdata
%  YDATA8:  line ydata
%  XDATA9:  line xdata
%  YDATA9:  line ydata
%  YDATA10:  line ydata
%  YDATA11:  line ydata
%  YDATA12:  line ydata
%  YDATA13:  line ydata
%  YDATA14:  line ydata
%  YDATA15:  line ydata
%  YDATA16:  line ydata
%  YDATA17:  line ydata
%  YDATA18:  line ydata
%  XDATA10:  line xdata
%  YDATA19:  line ydata
%  XDATA11:  line xdata
%  YDATA20:  line ydata
%  XDATA12:  line xdata
%  YDATA21:  line ydata
%  XDATA13:  line xdata
%  YDATA22:  line ydata
%  XDATA14:  line xdata
%  YDATA23:  line ydata
%  XDATA15:  line xdata
%  YDATA24:  line ydata
%  XDATA16:  line xdata
%  YDATA25:  line ydata
%  XDATA17:  line xdata
%  YDATA26:  line ydata
%  XDATA18:  line xdata
%  YDATA27:  line ydata
%  YDATA28:  line ydata
%  YDATA29:  line ydata
%  YDATA30:  line ydata
%  YDATA31:  line ydata
%  YDATA32:  line ydata
%  YDATA33:  line ydata
%  YDATA34:  line ydata
%  YDATA35:  line ydata
%  XDATA19:  line xdata
%  YDATA36:  line ydata
%  XDATA20:  line xdata
%  YDATA37:  line ydata
%  XDATA21:  line xdata
%  YDATA38:  line ydata
%  XDATA22:  line xdata
%  YDATA39:  line ydata
%  XDATA23:  line xdata
%  YDATA40:  line ydata
%  XDATA24:  line xdata
%  YDATA41:  line ydata
%  XDATA25:  line xdata
%  YDATA42:  line ydata
%  XDATA26:  line xdata
%  YDATA43:  line ydata
%  XDATA27:  line xdata
%  YDATA44:  line ydata
%  XDATA28:  line xdata
%  YDATA45:  line ydata
%  XDATA29:  line xdata
%  YDATA46:  line ydata
%  XDATA30:  line xdata
%  YDATA47:  line ydata
%  XDATA31:  line xdata
%  YDATA48:  line ydata
%  XDATA32:  line xdata
%  YDATA49:  line ydata
%  XDATA33:  line xdata
%  YDATA50:  line ydata
%  XDATA34:  line xdata
%  YDATA51:  line ydata
%  XDATA35:  line xdata
%  YDATA52:  line ydata
%  XDATA36:  line xdata
%  YDATA53:  line ydata
%  YDATA54:  line ydata
%  XDATA37:  line xdata
%  YDATA55:  line ydata
%  XDATA38:  line xdata
%  YDATA56:  line ydata
%  XDATA39:  line xdata
%  YDATA57:  line ydata
%  XDATA40:  line xdata
%  YDATA58:  line ydata
%  XDATA41:  line xdata
%  YDATA59:  line ydata
%  XDATA42:  line xdata
%  YDATA60:  line ydata
%  XDATA43:  line xdata
%  YDATA61:  line ydata
%  XDATA44:  line xdata
%  YDATA62:  line ydata

%  Auto-generated by MATLAB on 15-Aug-2019 10:32:32

% Create hggroup
hggroup('Tag','boxplot');

% Create line
line(XData1,YData1,'Tag','Upper Whisker','LineStyle','--');

% Create line
line(XData2,YData2,'Tag','Upper Whisker','LineStyle','--');

% Create line
line(XData3,YData3,'Tag','Upper Whisker','LineStyle','--');

% Create line
line(XData4,YData4,'Tag','Upper Whisker','LineStyle','--');

% Create line
line(XData5,YData5,'Tag','Upper Whisker','LineStyle','--');

% Create line
line(XData6,YData6,'Tag','Upper Whisker','LineStyle','--');

% Create line
line(XData7,YData7,'Tag','Upper Whisker','LineStyle','--');

% Create line
line(XData8,YData8,'Tag','Upper Whisker','LineStyle','--');

% Create line
line(XData9,YData9,'Tag','Upper Whisker','LineStyle','--');

% Create line
line(XData1,YData10,'Tag','Lower Whisker','LineStyle','--');

% Create line
line(XData2,YData11,'Tag','Lower Whisker','LineStyle','--');

% Create line
line(XData3,YData12,'Tag','Lower Whisker','LineStyle','--');

% Create line
line(XData4,YData13,'Tag','Lower Whisker','LineStyle','--');

% Create line
line(XData5,YData14,'Tag','Lower Whisker','LineStyle','--');

% Create line
line(XData6,YData15,'Tag','Lower Whisker','LineStyle','--');

% Create line
line(XData7,YData16,'Tag','Lower Whisker','LineStyle','--');

% Create line
line(XData8,YData17,'Tag','Lower Whisker','LineStyle','--');

% Create line
line(XData9,YData18,'Tag','Lower Whisker','LineStyle','--');

% Create line
line(XData10,YData19,'Tag','Upper Adjacent Value');

% Create line
line(XData11,YData20,'Tag','Upper Adjacent Value');

% Create line
line(XData12,YData21,'Tag','Upper Adjacent Value');

% Create line
line(XData13,YData22,'Tag','Upper Adjacent Value');

% Create line
line(XData14,YData23,'Tag','Upper Adjacent Value');

% Create line
line(XData15,YData24,'Tag','Upper Adjacent Value');

% Create line
line(XData16,YData25,'Tag','Upper Adjacent Value');

% Create line
line(XData17,YData26,'Tag','Upper Adjacent Value');

% Create line
line(XData18,YData27,'Tag','Upper Adjacent Value');

% Create line
line(XData10,YData28,'Tag','Lower Adjacent Value');

% Create line
line(XData11,YData29,'Tag','Lower Adjacent Value');

% Create line
line(XData12,YData12,'Tag','Lower Adjacent Value');

% Create line
line(XData13,YData30,'Tag','Lower Adjacent Value');

% Create line
line(XData14,YData31,'Tag','Lower Adjacent Value');

% Create line
line(XData15,YData32,'Tag','Lower Adjacent Value');

% Create line
line(XData16,YData33,'Tag','Lower Adjacent Value');

% Create line
line(XData17,YData34,'Tag','Lower Adjacent Value');

% Create line
line(XData18,YData35,'Tag','Lower Adjacent Value');

% Create line
line(XData19,YData36,'Tag','Box','Color',[0 0 1]);

% Create line
line(XData20,YData37,'Tag','Box','Color',[0 0 1]);

% Create line
line(XData21,YData38,'Tag','Box','Color',[0 0 1]);

% Create line
line(XData22,YData39,'Tag','Box','Color',[0 0 1]);

% Create line
line(XData23,YData40,'Tag','Box','Color',[0 0 1]);

% Create line
line(XData24,YData41,'Tag','Box','Color',[0 0 1]);

% Create line
line(XData25,YData42,'Tag','Box','Color',[0 0 1]);

% Create line
line(XData26,YData43,'Tag','Box','Color',[0 0 1]);

% Create line
line(XData27,YData44,'Tag','Box','Color',[0 0 1]);

% Create line
line(XData28,YData45,'Tag','Median','Color',[1 0 0]);

% Create line
line(XData29,YData46,'Tag','Median','Color',[1 0 0]);

% Create line
line(XData30,YData47,'Tag','Median','Color',[1 0 0]);

% Create line
line(XData31,YData48,'Tag','Median','Color',[1 0 0]);

% Create line
line(XData32,YData49,'Tag','Median','Color',[1 0 0]);

% Create line
line(XData33,YData50,'Tag','Median','Color',[1 0 0]);

% Create line
line(XData34,YData51,'Tag','Median','Color',[1 0 0]);

% Create line
line(XData35,YData52,'Tag','Median','Color',[1 0 0]);

% Create line
line(XData36,YData53,'Tag','Median','Color',[1 0 0]);

% Create line
line(XData1,YData54,'Tag','Outliers','MarkerEdgeColor',[1 0 0],'Marker','+',...
    'LineStyle','none');

% Create line
line(XData37,YData55,'Tag','Outliers','MarkerEdgeColor',[1 0 0],...
    'Marker','+',...
    'LineStyle','none');

% Create line
line(XData38,YData56,'Tag','Outliers','MarkerEdgeColor',[1 0 0],...
    'Marker','+',...
    'LineStyle','none');

% Create line
line(XData39,YData57,'Tag','Outliers','MarkerEdgeColor',[1 0 0],...
    'Marker','+',...
    'LineStyle','none');

% Create line
line(XData40,YData58,'Tag','Outliers','MarkerEdgeColor',[1 0 0],...
    'Marker','+',...
    'LineStyle','none');

% Create line
line(XData41,YData59,'Tag','Outliers','MarkerEdgeColor',[1 0 0],...
    'Marker','+',...
    'LineStyle','none');

% Create line
line(XData42,YData60,'Tag','Outliers','MarkerEdgeColor',[1 0 0],...
    'Marker','+',...
    'LineStyle','none');

% Create line
line(XData43,YData61,'Tag','Outliers','MarkerEdgeColor',[1 0 0],...
    'Marker','+',...
    'LineStyle','none');

% Create line
line(XData44,YData62,'Tag','Outliers','MarkerEdgeColor',[1 0 0],...
    'Marker','+',...
    'LineStyle','none');

